### ISSUE TITLE
Starting error

### ISSUE THREAD

**Issue by Nooobiecake** [itsmemac/VU-Pterodactyl#1]
`[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 0
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Checking server disk space usage, this could take a few seconds...
[Pterodactyl Daemon]: Updating process configuration files...
[Pterodactyl Daemon]: Ensuring file permissions are set correctly, this could take a few seconds...
container@pterodactyl~ Server marked as starting...
[Pterodactyl Daemon]: Pulling Docker container image, this could take a few minutes to complete...
Pulling from itsmemac/vu-pterodactyl 
Status: Image is up to date for ghcr.io/itsmemac/vu-pterodactyl:main 
Digest: sha256:0b632b7cc48b24eddb83856b80da761e77ed8b58a0cf25345f4a751776b6ab3d 
[Pterodactyl Daemon]: Finished pulling Docker container image
Running on Debian 11.4
Current timezone: Etc/UTC
wine-7.0
First launch will throw some errors. Ignore them
:/home/container$ if [ ! -f /home/container/activated ]; then wine ~/vu/client/vu.com -gamepath ~/bf3 -activate -o_mail ${EMAIL} -o_pass ${PASSWORD}; touch /home/container/activated; else wine ~/vu/client/vu.com -gamepath ~/bf3 -serverInstancePath "$(winepath -w ~/vu/instance)" -server -dedicated -listen 0.0.0.0:$SERVER_PORT -mHarmonyPort ${HARMONY} -RemoteAdminPort 0.0.0.0:${RCON}; fi
_XSERVTransmkdir: ERROR: euid != 0,directory /tmp/.X11-unix will not be created.
0108:fixme:wbemprox:client_security_SetBlanket 0F3247D0, 02500598, 10, 0, (null), 3, 3, 00000000, 0x00000000
0108:fixme:wbemprox:client_security_Release 0F3247D0
0108:fixme:wbemprox:client_security_SetBlanket 0F3247D0, 02500690, 10, 0, (null), 3, 3, 00000000, 0x00000000
0108:fixme:wbemprox:client_security_Release 0F3247D0
0108:fixme:wbemprox:client_security_SetBlanket 0F3247D0, 02500690, 10, 0, (null), 3, 3, 00000000, 0x00000000
0108:fixme:wbemprox:client_security_Release 0F3247D0
0108:fixme:ntdll:NtQuerySystemInformation info_class SYSTEM_PERFORMANCE_INFORMATION
0108:fixme:wbemprox:client_security_SetBlanket 0F3247D0, 02500678, 10, 0, (null), 3, 3, 00000000, 0x00000000
0108:fixme:wbemprox:client_security_Release 0F3247D0
0108:fixme:wbemprox:client_security_SetBlanket 0F3247D0, 02500678, 10, 0, (null), 3, 3, 00000000, 0x00000000
0108:fixme:wbemprox:client_security_Release 0F3247D0
0108:fixme:wbemprox:client_security_SetBlanket 0F3247D0, 02500678, 10, 0, (null), 3, 3, 00000000, 0x00000000
0108:fixme:wbemprox:client_security_Release 0F3247D0
011c:fixme:heap:RtlSetHeapInformation 00000000 1 00000000 0 stub
wine: Unhandled page fault on read access to 000000B8 at address 1000653A (thread 0124), starting debugger...
012c:fixme:imm:ImeSetActiveContext (0x2402e8, 1): stub
012c:fixme:imm:ImmReleaseContext (00010070, 002402E8): stub
0050:fixme:imm:ImeSetActiveContext (0x38e70, 0): stub
0050:fixme:imm:ImmReleaseContext (0000000000010020, 0000000000038E70): stub
container@pterodactyl~ Server marked as offline...
[Pterodactyl Daemon]: ---------- Detected server process in a crashed state! ----------
[Pterodactyl Daemon]: Exit code: 0
[Pterodactyl Daemon]: Out of memory: false
[Pterodactyl Daemon]: Aborting automatic restart, last crash occurred less than 60 seconds ago.`

**Comment by itsmemac** [comment]
It seems you have started the server with default credentials in startup stab
Hence server is not working

Delete `activated` file and enter your EA credentials in startup tab
And start the server 

It's mentioned in readme to not start the server with default credentials

**Comment by Nooobiecake** [comment]
Okay ill try that.

So i have to "install" the server (with login credentials), then delete `activated` file.
confirm my credentials. and then start? 

Thanks for the info! much appreciated.
and great work!

**Comment by itsmemac** [comment]
> Okay ill try that.
> 
> So i have to "install" the server (with login credentials), then delete `activated` file.
> confirm my credentials. and then start? 
> 
> Thanks for the info! much appreciated.
> and great work!
> 

Since you have already installed
Just deleted the `activated` file and enter you credentials in startup tab of your - server and start the server
No reinstall needed
