### ISSUE TITLE
Pterodactyl Startup Issue

### ISSUE THREAD

**Issue by Phantom6422** [itsmemac/VU-Pterodactyl#2]
I'm still new to this but what does this mean and how do I solve it?
![Screenshot 2022-08-10 205742](https://user-images.githubusercontent.com/84639391/183907355-ae218285-dd0a-4bbc-b34e-9d819b469f63.png)

I would be appreciate if you can help me :>

**Comment by itsmemac** [comment]
The image you are using is a Java 17 egg (mostly minecraft) which isn't related to this egg repo which is for Venice Unleashed.
Your pterodactyl instance is failing to create container hence reach out to Pterodactyl support
https://discord.com/invite/pterodactyl
