### ISSUE TITLE
Pterodactyl not registering as running

### ISSUE THREAD

**Issue by matt-alton** [itsmemac/VU-Pterodactyl#3]
Hello,

Firstly, a great egg to make BF3 work in Ptero and save me from Windows or Wine on desktop!

I've been running this for several months and in that time I've never been able to get Pterodactyl to register the server as running. Usually, this wouldn't bother me but I have a custom plugin tracking player counts that won't start querying players until the server is marked as running.

The last line my console printed on a restart I just did was
```
[2022-11-10 20:05:59+00:00] [info] Game successfully registered with Zeus. The s
erver is now accepting connections.
```

My start configuration is:
```
{
    "done": "Game successfully registered with Zeus"
}
```

I've changed the search criteria to different things and redeployed the server but it still never marks it as online. All my other servers using different eggs get marked as running so it appears to be just this one. Do you have any suggestions as to what could be causing this?

Regards,
Matt.

**Comment by matt-alton** [comment]
If I type "Game successfully registered with Zeus" in the console it marks the server as running 😕

**Comment by itsmemac** [comment]
Hi @matt-alton 
I have been trying to figure out whats causing this issue
Ptero seems to not register the running status for VU egg alone but after sometime, it automatically marks the server as running.

> If I type "Game successfully registered with Zeus" in the console it marks the server as running 😕

thanks to this update. Seems to be something to do with Ptero running status message detection.

Will get back to you on this soon

**Comment by matt-alton** [comment]
I'll hedge my bets on Ptero not interacting with Wine very well or some regex being needed to work around the bracketed number outputs before the string being searched.

**Comment by itsmemac** [comment]
> I'll hedge my bets on Ptero not interacting with Wine very well or some regex being needed to work around the bracketed number outputs before the string being searched.

I think so as well since i was able to get the running status correctly dectected previously but this started to appear in the last few months

**Comment by itsmemac** [comment]
To Update on this issue

Tried different solutions with Ptero discord and multiple combinations of start configs
Still unable to get the startup detection to work

Seems to be how Ptero reads console for wine related games

Checking other solutions as well and will keep posted regarding the fix.

**Comment by matt-alton** [comment]
Thanks for continuing to look into this. An observation I've made is if I restart wings the server will change to running. In the meantime, I've just added an echo of the done string into my startup command so it always indicates as running - a bit of a short circuit but works around the stuck in starting for my purposes.

**Comment by itsmemac** [comment]
Heyo @matt-alton 
Seems to be how wine works
https://github.com/pterodactyl/panel/issues/2937

Nothing much can be done since its how wine commands are being recognized

Will check this in the future if there is any solution.

Closing this issue for now
